version: '2'
services:
  nodeapp:
    container_name: nodeapp
    build: containers/nodeapp
    env_file:
      - .globals
    volumes:
      - ./containers/keddell/data:/data
  nginx:
    container_name: nginx
    build: containers/nginx
    links:
      - nodeapp
    ports:
      - "8000:5000"
